services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: ecommerce_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"


  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: ecommerce_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        PLAINTEXT_INTERNAL:PLAINTEXT

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://localhost:9092,
        PLAINTEXT_INTERNAL://kafka:29092

      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9092,
        PLAINTEXT_INTERNAL://0.0.0.0:29092

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"


  postgres:
    image: postgres:15
    container_name: ecommerce_postgres

    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass

    ports:
      - "5432:5432"

    volumes:
      - ecommerce_postgres_data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql


  pgadmin:
    image: dpage/pgadmin4:8
    container_name: ecommerce_pgadmin

    depends_on:
      - postgres

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"


  spark:
    image: apache/spark:4.0.1
    container_name: ecommerce_spark

    user: root

    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_PROFILE: default

    volumes:
      - ./:/opt/ecommerce
      - ${USERPROFILE}/.aws:/root/.aws:ro

    working_dir: /opt/ecommerce

    entrypoint:
      - /bin/bash
      - -c

    command:
      - tail -f /dev/null


volumes:
  ecommerce_postgres_data: